@startuml
actor EmpresaParceira as EP
participant EmpresaParceiraController as EPC
participant EmpresaParceiraService as EPS
participant VantagemRepository as VR
participant BancoDeDados as BD

EP -> EPC : Login
EPC -> EPS : Validar Credenciais
EPS -> BD : Consultar Credenciais no Banco de Dados
BD --> EPS : Credenciais Válidas
EPS --> EPC : Acesso Concedido
EPC --> EP : Acesso Concedido

EP -> EPC : Solicitar Cadastro de Vantagem (nome, descrição, foto, custo em moedas)
EPC -> EPS : Validar e processar cadastro
EPS -> BD : Verificar se empresa está cadastrada
BD --> EPS : Empresa Válida
EPS -> VR : Armazenar dados da nova vantagem

VR --> EPS : Confirmação de Armazenamento
EPS --> EPC : Vantagem Cadastrada com Sucesso
EPC --> EP : Vantagem Cadastrada com Sucesso

@enduml
